// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0bed6748-bc99-49af-983e-7c5be51aebb1";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAlarmControlChange();
void onAutoModeChange();
void onFanControlChange();

float humidity;
float temperature;
int airQuality;
int smokeLevel;
bool alarmControl;
bool autoMode;
bool fanControl;
bool safetyStatus;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(airQuality, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(smokeLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(alarmControl, READWRITE, ON_CHANGE, onAlarmControlChange);
  ArduinoCloud.addProperty(autoMode, READWRITE, ON_CHANGE, onAutoModeChange);
  ArduinoCloud.addProperty(fanControl, READWRITE, ON_CHANGE, onFanControlChange);
  ArduinoCloud.addProperty(safetyStatus, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
